site_name: Sain
site_description: "A Simple Signature Capture Library"
site_author: "Joel Kanyi"
site_url: "https://joelkanyi.github.io/sain/"
repo_name: sain
repo_url: "https://github.com/joelkanyi/sain"
copyright: "Copyright &copy; 2024 Joel Kanyi"
edit_uri: "tree/main/docs/"
docs_dir: docs
remote_branch: gh-pages

theme:
  name: material
  features:
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: 'teal'
      accent: 'teal'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: 'light blue'
      accent: 'light blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  plugins:
    - macros # for variables like git.tag (requires mkdocs-macros-plugin)
    - search

  markdown_extensions:
    - admonition # for info/warn/tip sections
    - attr_list # for anchors in definition lists
    - def_list # for definition lists (stomp config)
    - footnotes
    - toc:
        permalink: true
    - pymdownx.emoji
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tabbed

  nav:
#    - 'Overview': index.md
#    - 'Getting Started': getting-started.md
#    - 'Usage': usage.md
    - 'API Reference': /docs/kdoc/index.html
#    - 'Samples': samples.md
#    - 'License': license.md

  extra:
    social:
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/_joelkanyi
        name: "Joel on Twitter"
    versions:
      jackson: 2.17.1
      ktor: 2.3.11
      kotlinxSerialization: 1.6.3
      moshi: 1.15.1
      tyrus: 2.1.5

  copyright: Copyright &copy; 2023 - 2024 Joel Kanyi