site_name: Sain
site_description: "A Simple Signature Capture Library"
site_author: "Joel Kanyi"
site_url: "https://joelkanyi.github.io/sain/"
repo_name: sain
repo_url: "https://github.com/joelkanyi/sain"
copyright: "Copyright &copy; 2024 Joel Kanyi"
edit_uri: "tree/main/docs/"
docs_dir: docs
remote_branch: gh-pages

nav:
  - 'Overview': index.md
  - 'Getting Started': get-started.md
  - 'Usage': usage.md
  - 'API Reference': kdoc/sain/index.html
  - 'Demo': samples.md
  - 'License': license.md

theme:
  name: 'material'
  language: 'en'
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tilde