[versions]
kotlin = "1.9.22"
agp = "8.2.2"
appcompat = "1.6.1"
core-ktx = "1.12.0"
material3 = "1.2.0"
compose = "1.6.2"
compose-compiler = "1.5.8"
compose-activity = "1.8.2"
spotless = "6.25.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }


[plugins]
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

