name: Build

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'mkdocs.yml'
      - 'docs/**'
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Cache konan directory
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts', 'buildSrc/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Linux build
        run: |
          ./gradlew :sample:shared:assemble --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"