name: Build Linux

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

env:
  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  GPG_KEY: ${{ secrets.GPG_KEY }}
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Cache konan directory
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts', 'buildSrc/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Linux build
        run: |
          ./gradlew :sain:assemble --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"