name: Build All

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  build-linux:
    name: Build Linux
    uses: ./.github/workflows/build-linux.yml

  build-macos:
    name: Build macOS
    uses: ./.github/workflows/build-macos.yml

  build-windows:
    name: Build Windows
    uses: ./.github/workflows/build-windows.yml