name: Publish docs

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_docs:
    runs-on: macos-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate KDocs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs Material
        run: pip install mkdocs-material mkdocs-macros-plugin

      - name: Deploy doc to GitHub pages
        # --strict aborts on any warning
        # --force forces the push to the repo (gh-pages branch)
        run: mkdocs gh-deploy --strict --force